mysql:
  secrets:
    MYSQL_ROOT_PASSWORD: placeholder
    MYSQL_USER: placeholder
    MYSQL_PASSWORD: placeholder

todoapp:
  namespace: todoapp
  image:
    repository: ikulyk404/todoapp
    tag: "4.0.1"

  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
    limits:
      memory: "256Mi"
      cpu: "150m"

  secret:
    SECRET_KEY: placeholder
    DB_NAME: placeholder
    DB_USER: placeholder
    DB_PASSWORD: placeholder
    DB_HOST: placeholder

  hpa:
    minReplicas: 2
    maxReplicas: 5
    cpu:
      avarageUtilization: 70
    memory:
      avarageUtilization: 70

  volumes:
    persistentVolume:
      capacity: "1Gi"
    persistentVolumeClaim:
      requestStorage: "1Gi"